# Generated by Django 4.2 on 2023-05-05 02:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('travels', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='image',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.destination'),
        ),
        migrations.AddField(
            model_name='experience',
            name='destination',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.destination'),
        ),
        migrations.AddField(
            model_name='destination',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.city'),
        ),
        migrations.AddField(
            model_name='city',
            name='province',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.province'),
        ),
        migrations.AddField(
            model_name='address',
            name='city',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.city'),
        ),
    ]
