# Generated by Django 4.2 on 2023-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='name',
            field=models.CharField(max_length=50),
        ),
    ]
