# Generated by Django 4.2 on 2023-05-30 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0003_alter_experience_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='experience',
            name='description',
            field=models.TextField(),
        ),
    ]
