# Generated by Django 4.2 on 2023-05-30 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0004_alter_experience_description'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='accommodation',
        ),
        migrations.RemoveField(
            model_name='package',
            name='experience',
        ),
    ]
