# Generated by Django 4.2 on 2023-05-31 01:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0007_alter_imagedestination_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='rate',
            field=models.FloatField(default=0),
        ),
    ]
