# Generated by Django 4.2 on 2023-05-31 12:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0008_package_rate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='imageaccommodation',
            name='url',
            field=models.FileField(upload_to='destinos-cba'),
        ),
        migrations.CreateModel(
            name='ImageExperience',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url', models.FileField(upload_to='destinos-cba')),
                ('title', models.CharField(max_length=30)),
                ('experience', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='travels.experience')),
            ],
        ),
    ]
