# Generated by Django 4.2 on 2023-06-18 19:07

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('travels', '0009_alter_imageaccommodation_url_imageexperience'),
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('card_number', models.CharField(max_length=20)),
                ('card_type', models.CharField(max_length=10)),
                ('name', models.CharField(max_length=30)),
                ('dni', models.CharField(max_length=10)),
                ('cvv', models.CharField(max_length=3)),
                ('exp_month', models.CharField(max_length=2)),
                ('exp_year', models.CharField(max_length=4)),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='amount',
            field=models.FloatField(default=0.0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NON', 'None'), ('ACC', 'Accepted'), ('REJ', 'Rejected'), ('EXP', 'Expired')], default='NON', max_length=3),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='travels.paymentinfo'),
        ),
        migrations.DeleteModel(
            name='Payment',
        ),
    ]
