# Generated by Django 4.2 on 2023-05-30 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='photo',
            field=models.CharField(blank=True, default='/assets/img/default.png', max_length=255, null=True),
        ),
    ]
